twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
        nomBlog: "Le Saint Blog d'Esteban"
        categoryRepository: "@App\\Repository\\CategoryRepository"

when@test:
    twig:
        strict_variables: true
